// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9uUAbY5YTQLP6f-_-PN1Rj_N4G6QTCxM',
    appId: '1:332971276820:web:79341506d4d7cfbc194501',
    messagingSenderId: '332971276820',
    projectId: 'chat-app-c6ab9',
    authDomain: 'chat-app-c6ab9.firebaseapp.com',
    storageBucket: 'chat-app-c6ab9.firebasestorage.app',
    measurementId: 'G-1RNV3BSKQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZC-6gT7HuT2kw8MHJhjKMnh3699FKAjw',
    appId: '1:332971276820:android:91275b11718ce052194501',
    messagingSenderId: '332971276820',
    projectId: 'chat-app-c6ab9',
    storageBucket: 'chat-app-c6ab9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq7h3iqBV8RAx3G8tSYQdysRlqFZbjEVo',
    appId: '1:332971276820:ios:dbd73996459a7965194501',
    messagingSenderId: '332971276820',
    projectId: 'chat-app-c6ab9',
    storageBucket: 'chat-app-c6ab9.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq7h3iqBV8RAx3G8tSYQdysRlqFZbjEVo',
    appId: '1:332971276820:ios:dbd73996459a7965194501',
    messagingSenderId: '332971276820',
    projectId: 'chat-app-c6ab9',
    storageBucket: 'chat-app-c6ab9.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9uUAbY5YTQLP6f-_-PN1Rj_N4G6QTCxM',
    appId: '1:332971276820:web:4d3f12ae558343eb194501',
    messagingSenderId: '332971276820',
    projectId: 'chat-app-c6ab9',
    authDomain: 'chat-app-c6ab9.firebaseapp.com',
    storageBucket: 'chat-app-c6ab9.firebasestorage.app',
    measurementId: 'G-BT4530YFC4',
  );
}
